site_name: Bear Base API
site_url: https://base.api.bearrobotics.ai/
copyright: Copyright 2025 Bear Robotics, Inc. All rights reserved.
theme:
  name: 'material'
  features:
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.tabs
    - toc.follow
    - content.tabs.link
  palette:
    primary: custom
  favicon: assets/favicon.png
  logo: assets/bear_logo_white.png
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: True
      toc_depth: 4
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
nav:
  - Overview:
    - index.md
  - API Reference:
    - v1.3:
      - gRPC API:
        - Mission: v1.3/resources/Mission.md
        - Locations & Maps: v1.3/resources/LocationsAndMaps.md
        - Localization & Navigation: v1.3/resources/LocalizationAndNavigation.md
        - Robot Status: v1.3/resources/RobotStatus.md
        - Robot System: v1.3/resources/RobotSystem.md
        - Settings: v1.3/resources/Settings.md
        - Servi: v1.3/resources/Servi.md
        - Carti: v1.3/resources/Carti.md
    - v1.2:
      - gRPC API:
        - Mission: v1.2/resources/Mission.md
        - Locations & Maps: v1.2/resources/LocationsAndMaps.md
        - Localization & Navigation: v1.2/resources/LocalizationAndNavigation.md
        - Robot Status: v1.2/resources/RobotStatus.md
        - Robot System: v1.2/resources/RobotSystem.md
        - Settings: v1.2/resources/Settings.md
        - Servi: v1.2/resources/Servi.md
        - Carti: v1.2/resources/Carti.md
    - v0.1:
      - Services:
        - RobotAPIService: v0.1/robot/RobotApiService.md
      - Message Types:
        - Common:
          - Annotations: v0.1/common/Annotations.md
          - Math: v0.1/common/Math.md
        - Location:
          - Annotation: v0.1/location/Annotation.md
          - Location: v0.1/location/Location.md
          - Map: v0.1/location/Map.md
          - Types: v0.1/location/Types.md
          - Zones: v0.1/location/Zones.md
        - Robot:
          - Localization: v0.1/robot/Localization.md
          - Mission: v0.1/robot/Mission.md
          - Network: v0.1/robot/Network.md
          - Robot: v0.1/robot/Robot.md
          - Settings: v0.1/robot/Settings.md
          - Status: v0.1/robot/Status.md
          - System: v0.1/robot/System.md
      - Settings: v0.1/settings.md
    - v0.0:
      - Services:
        - RobotAPIService: v0.0/robot/RobotApiService.md
      - Message Types:
        - Common:
          - Annotations: v0.0/common/Annotations.md
          - Math: v0.0/common/Math.md
        - Robot:
          - Network: v0.0/robot/Network.md
          - Robot: v0.0/robot/Robot.md
          - Status: v0.0/robot/Status.md
          - System: v0.0/robot/System.md
  - Core Concepts:
    - Mission: concepts/mission.md
    - Localization: concepts/localization.md
    - Location: concepts/location.md
    - Status: concepts/status.md
  - Guides:
    - Setup:
      - Network Connectivity: guides/setup/setup_network.md
      - Examples: guides/setup/examples_python.md
    - Troubleshooting: guides/troubleshooting.md
  - Changelog:
    - v1.3: changelog/v1.3.md
    - v1.2: changelog/v1.2.md
    - v0.1: changelog/v0.1.md
    - v0.0: changelog/v0.0.md
